//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Sport.ui.BBC {
    
    
    /// <summary>
    /// Category class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Category {
        
        /// <summary>
        /// PanelTop1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.ui.BBC.PanelTop PanelTop1;
        
        /// <summary>
        /// PanelTinBongda1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.ui.BBC.PanelTinBongda PanelTinBongda1;
        
        /// <summary>
        /// PanelCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.ui.BBC.PanelCateBox PanelCateBox1;
        
        /// <summary>
        /// PanelCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.ui.BBC.PanelCateBox PanelCateBox2;
        
        /// <summary>
        /// PanelCateBox3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.ui.BBC.PanelCateBox PanelCateBox3;
    }
}
