//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.English {
    
    
    /// <summary>
    /// _Default class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class _Default {
        
        /// <summary>
        /// PanelTopNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelTopNews PanelTopNews1;
        
        /// <summary>
        /// PanelTopStories1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelTopStories PanelTopStories1;
        
        /// <summary>
        /// PanelAdvB1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvB1 PanelAdvB1_1;
        
        /// <summary>
        /// PanelSmallCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox1;
        
        /// <summary>
        /// PanelSmallCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox2;
        
        /// <summary>
        /// PanelSmallCateBox3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox3;
        
        /// <summary>
        /// PanelSmallCateBox4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox4;
        
        /// <summary>
        /// PanelSmallCateBox5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox5;
        
        /// <summary>
        /// PanelSmallCateBox6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox6;
        
        /// <summary>
        /// PanelSmallCateBox7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox7;
        
        /// <summary>
        /// PanelSmallCateBox8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox8;
        
        /// <summary>
        /// PanelSmallCateBox9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox9;
        
        /// <summary>
        /// PanelSmallCateBox10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox10;
        
        /// <summary>
        /// PanelAdvB2_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvB2 PanelAdvB2_1;
        
        /// <summary>
        /// PanelBigCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelBigCateBox PanelBigCateBox1;
        
        /// <summary>
        /// PanelBigCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Homepage.PanelBigCateBox PanelBigCateBox2;
        
        /// <summary>
        /// PanelAdvC1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvC1 PanelAdvC1_1;
        
        /// <summary>
        /// PanelCateLatestNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Category.PanelCateLatestNews PanelCateLatestNews1;
        
        /// <summary>
        /// PanelVideoClip1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelVideoClip PanelVideoClip1;
        
        /// <summary>
        /// PanelTellUs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelTellUs PanelTellUs1;
        
        /// <summary>
        /// PanelAdvC2_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvC2 PanelAdvC2_2;
        
        /// <summary>
        /// PanelInFocus1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelInFocus PanelInFocus1;
        
        /// <summary>
        /// PanelAdvertisement1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelAdvertisement PanelAdvertisement1;
    }
}
