//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.English {
    
    
    /// <summary>
    /// NewsDetail class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class NewsDetail {
        
        /// <summary>
        /// PanelContentCateName1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentCateName PanelContentCateName1;
        
        /// <summary>
        /// PanelContentNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentNews PanelContentNews1;
        
        /// <summary>
        /// PaneSurvey1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.UserControls.Survey.PaneSurvey PaneSurvey1;
        
        /// <summary>
        /// PanelContentFeedback1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentFeedback PanelContentFeedback1;
        
        /// <summary>
        /// PanelContentReadOn1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentReadOn PanelContentReadOn1;
        
        /// <summary>
        /// PanelContentListFeedback1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentListFeedback PanelContentListFeedback1;
        
        /// <summary>
        /// PanelAdvB1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvB1 PanelAdvB1_1;
        
        /// <summary>
        /// PanelAdvC1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvC1 PanelAdvC1_1;
        
        /// <summary>
        /// PanelTopStory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelTopStory PanelTopStory1;
        
        /// <summary>
        /// PanelLatestNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelLatestNews PanelLatestNews1;
        
        /// <summary>
        /// PanelTellUs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelTellUs PanelTellUs1;
        
        /// <summary>
        /// PanelAdvC1_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.Advertisements.PanelAdvC1 PanelAdvC1_2;
        
        /// <summary>
        /// PanelInFocus1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelInFocus PanelInFocus1;
        
        /// <summary>
        /// PanelAdvertisement1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.PanelAdvertisement PanelAdvertisement1;
    }
}
