//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Sport {
    
    
    /// <summary>
    /// Categories class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Categories {
        
        /// <summary>
        /// PanelTop1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Categories.PanelTop PanelTop1;
        
        /// <summary>
        /// PanelAdvC1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC1 PanelAdvC1_1;
        
        /// <summary>
        /// PanelAdvB1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB1 PanelAdvB1_1;
        
        /// <summary>
        /// PanelCateContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Categories.PanelCateContent PanelCateContent1;
        
        /// <summary>
        /// PanelMostRead1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Categories.PanelMostRead PanelMostRead1;
        
        /// <summary>
        /// PanelSurvey1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.UserControls.Survey.PaneSurvey PanelSurvey1;
        
        /// <summary>
        /// PanelContentImageSport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentImageSport PanelContentImageSport1;
        
        /// <summary>
        /// PanelAdvC6_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC6 PanelAdvC6_1;
        
        /// <summary>
        /// PanelSmallCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox1;
        
        /// <summary>
        /// PanelSmallCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox2;
        
        /// <summary>
        /// PanelAdvC7_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC7 PanelAdvC7_1;
        
        /// <summary>
        /// PanelAdvC4_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC4 PanelAdvC4_1;
        
        /// <summary>
        /// PanelTheodong1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.PanelTheodong PanelTheodong1;
    }
}
