//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.WebSites.Clip {
    
    
    /// <summary>
    /// Category class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Category {
        
        /// <summary>
        /// PanelCategoryPlaylist1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.ui._3g.PanelCategoryPlaylist PanelCategoryPlaylist1;
        
        /// <summary>
        /// PanelAdvC_1_3_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelAdvC_1_3 PanelAdvC_1_3_1;
        
        /// <summary>
        /// PanelCate3gContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelCate3gContent PanelCate3gContent1;
        
        /// <summary>
        /// PanelClipNoibat1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.ui._3g.PanelClipNoibat PanelClipNoibat1;
        
        /// <summary>
        /// PanelTamdiem3g1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelTamdiem3g PanelTamdiem3g1;
        
        /// <summary>
        /// PanelAdvC_6_14_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelAdvC_6_14 PanelAdvC_6_14_1;
        
        /// <summary>
        /// PanelAdvertisement1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.PanelAdvertisement PanelAdvertisement1;
    }
}
