//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.AddOn.VCard {
    
    public partial class Login {
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.Label lblLoginName;
        protected Telerik.Web.UI.RadTextBox txtLoginName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.Label lblPassword;
        protected Telerik.Web.UI.RadTextBox txtPassword;
        protected Telerik.Web.UI.RadCaptcha radCaptchaLogin;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
