//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.V1.UserControls {
    
    
    /// <summary>
    /// PanelHoptac class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class PanelHoptac {
        
        /// <summary>
        /// PanelCateBoxHoptac1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac1;
        
        /// <summary>
        /// PanelCateBoxHoptac2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac2;
        
        /// <summary>
        /// PanelCateBoxHoptac3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac3;
        
        /// <summary>
        /// PanelCateBoxHoptac4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac4;
        
        /// <summary>
        /// PanelCateBoxHoptac5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac5;
        
        /// <summary>
        /// PanelCateBoxHoptac6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac6;
        
        /// <summary>
        /// PanelCateBoxHoptac7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelCateBoxHoptac PanelCateBoxHoptac7;
    }
}
