//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.AddOn.Union.UserControls {
    
    
    /// <summary>
    /// PanelRight class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class PanelRight {
        
        /// <summary>
        /// PanelBirthday1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.AddOn.Union.UserControls.PanelBirthday PanelBirthday1;
        
        /// <summary>
        /// PanelRSS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.AddOn.Union.UserControls.PanelRSS PanelRSS1;
        
        /// <summary>
        /// PanelRSS3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.AddOn.Union.UserControls.PanelRSS PanelRSS3;
        
        /// <summary>
        /// PanelRSS4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.AddOn.Union.UserControls.PanelRSS PanelRSS4;
        
        /// <summary>
        /// PanelRSS2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.AddOn.Union.UserControls.PanelRSS PanelRSS2;
    }
}
