//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.V1.UserControls.Homepage {
    
    
    /// <summary>
    /// PanelLeft class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class PanelLeft {
        
        /// <summary>
        /// PanelCategory7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory7;
        
        /// <summary>
        /// PanelCategory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory1;
        
        /// <summary>
        /// PanelCategory2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory2;
        
        /// <summary>
        /// PanelCategory8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory8;
        
        /// <summary>
        /// PanelAdvB_2_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelAdvB_2 PanelAdvB_2_1;
        
        /// <summary>
        /// PanelCategory9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory9;
        
        /// <summary>
        /// PanelCategory3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory3;
        
        /// <summary>
        /// PanelCategory4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory4;
        
        /// <summary>
        /// PanelCategory5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory5;
        
        /// <summary>
        /// PanelAdvB_3_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelAdvB_3 PanelAdvB_3_1;
        
        /// <summary>
        /// PanelCategory6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory6;
        
        /// <summary>
        /// PanelCategory10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory10;
        
        /// <summary>
        /// PanelCategory11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory11;
        
        /// <summary>
        /// PanelCategory12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCategory PanelCategory12;
    }
}
