//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Clip.ui._3g {
    
    
    /// <summary>
    /// Detail class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Detail {
        
        /// <summary>
        /// PanelArticlePlaylist1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.ui._3g.PanelArticlePlaylist PanelArticlePlaylist1;
        
        /// <summary>
        /// PanelAdvC_1_3_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelAdvC_1_3 PanelAdvC_1_3_1;
        
        /// <summary>
        /// rptMore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptMore;
        
        /// <summary>
        /// PanelClipNoibat1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.ui._3g.PanelClipNoibat PanelClipNoibat1;
        
        /// <summary>
        /// PanelTamdiem3g1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelTamdiem3g PanelTamdiem3g1;
        
        /// <summary>
        /// PanelCateBox1_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelCateBox1 PanelCateBox1_2;
        
        /// <summary>
        /// PanelAdvC_6_14_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Categories.PanelAdvC_6_14 PanelAdvC_6_14_1;
        
        /// <summary>
        /// PanelAdvertisement1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.PanelAdvertisement PanelAdvertisement1;
    }
}
