//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.V1.ui.vanhoa {
    
    
    /// <summary>
    /// Category class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Category {
        
        /// <summary>
        /// PanelCateTicker1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelCateTicker PanelCateTicker1;
        
        /// <summary>
        /// PanelCateHotNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelCateHotNews PanelCateHotNews1;
        
        /// <summary>
        /// PanelCateCenterPoint1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelCateCenterPoint PanelCateCenterPoint1;
        
        /// <summary>
        /// PanelCateHotSlide1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelCateHotSlide PanelCateHotSlide1;
        
        /// <summary>
        /// PanelAdvC_1_3_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelAdvC_1_3 PanelAdvC_1_3_2;
        
        /// <summary>
        /// PanelAdvB_1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelAdvB_1 PanelAdvB_1_1;
        
        /// <summary>
        /// PanelCateContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelCateContent PanelCateContent1;
        
        /// <summary>
        /// PanelOtherNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelOtherNews PanelOtherNews1;
        
        /// <summary>
        /// PanelCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCateBox PanelCateBox2;
        
        /// <summary>
        /// PanelMostRead1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelMostRead PanelMostRead1;
        
        /// <summary>
        /// PanelAdvC_4_5_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelAdvC_4_5 PanelAdvC_4_5_1;
        
        /// <summary>
        /// PanelCateImageNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelCateImageNews PanelCateImageNews1;
        
        /// <summary>
        /// PanelCateBox1_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelCateBox1 PanelCateBox1_2;
        
        /// <summary>
        /// PaneSurvey1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.UserControls.Survey.PaneSurvey PaneSurvey1;
        
        /// <summary>
        /// PanelAdvC_17_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Homepage.PanelAdvC_17 PanelAdvC_17_1;
        
        /// <summary>
        /// PanelAdvC_6_14_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.Categories.PanelAdvC_6_14 PanelAdvC_6_14_1;
        
        /// <summary>
        /// PanelAdvertisement1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.PanelAdvertisement PanelAdvertisement1;
    }
}
