//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Clip.UserControls.Homepage {
    
    
    /// <summary>
    /// PanelRight class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class PanelRight {
        
        /// <summary>
        /// PanelCateBoxTuan1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelCateBoxTuan PanelCateBoxTuan1;
        
        /// <summary>
        /// PanelCateBoxVNR1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelCateBoxVNR PanelCateBoxVNR1;
        
        /// <summary>
        /// PanelAdvC_5_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelAdvC_5 PanelAdvC_5_1;
        
        /// <summary>
        /// PanelCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelCateBox PanelCateBox1;
        
        /// <summary>
        /// PanelInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelInfo PanelInfo1;
        
        /// <summary>
        /// PanelMostRead1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelMostRead PanelMostRead1;
        
        /// <summary>
        /// PanelAdvC_6_7_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelAdvC_6_7 PanelAdvC_6_7_1;
        
        /// <summary>
        /// PanelCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelCateBox PanelCateBox2;
        
        /// <summary>
        /// PanelPoll1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelPoll PanelPoll1;
        
        /// <summary>
        /// PanelCateBox1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelCateBox1 PanelCateBox1_1;
        
        /// <summary>
        /// PanelAdvC_17_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelAdvC_17 PanelAdvC_17_1;
        
        /// <summary>
        /// PanelAdvC_8_16_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Clip.UserControls.Homepage.PanelAdvC_8_16 PanelAdvC_8_16_1;
    }
}
