//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Sport {
    
    
    /// <summary>
    /// _Default class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class _Default {
        
        /// <summary>
        /// PanelTopNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelTopNews PanelTopNews1;
        
        /// <summary>
        /// PanelHotNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelHotNews PanelHotNews1;
        
        /// <summary>
        /// PanelLiveScore1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelLiveScore PanelLiveScore1;
        
        /// <summary>
        /// PanelAdvC1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC1 PanelAdvC1_1;
        
        /// <summary>
        /// PanelTrungthuong1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelTrungthuong PanelTrungthuong1;
        
        /// <summary>
        /// PanelBBCCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBBCCateBox PanelBBCCateBox1;
        
        /// <summary>
        /// PanelAdvB1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB1 PanelAdvB1_1;
        
        /// <summary>
        /// PanelBigCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox1;
        
        /// <summary>
        /// PanelBigCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox2;
        
        /// <summary>
        /// PanelAdvB2_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB2 PanelAdvB2_1;
        
        /// <summary>
        /// PanelBigCateBox3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox3;
        
        /// <summary>
        /// PanelBigCateBox4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox4;
        
        /// <summary>
        /// PanelAdvB3_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB3 PanelAdvB3_1;
        
        /// <summary>
        /// PanelBigCateBox5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox5;
        
        /// <summary>
        /// PanelBigCateBox6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox6;
        
        /// <summary>
        /// PanelAdvB4_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB4 PanelAdvB4_1;
        
        /// <summary>
        /// PanelBigCateBox7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox7;
        
        /// <summary>
        /// PanelBigCateBox8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox8;
        
        /// <summary>
        /// PanelAdvB5_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB5 PanelAdvB5_1;
        
        /// <summary>
        /// PanelBigCateBox9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox9;
        
        /// <summary>
        /// PanelBigCateBox10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelBigCateBox PanelBigCateBox10;
        
        /// <summary>
        /// PanelClip1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelClip PanelClip1;
        
        /// <summary>
        /// PanelAdvC2_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC2 PanelAdvC2_1;
        
        /// <summary>
        /// PanelMostRead1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.PanelMostRead PanelMostRead1;
        
        /// <summary>
        /// PanelAdvC3_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC3 PanelAdvC3_1;
        
        /// <summary>
        /// PanelSurvey1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.UserControls.Survey.PaneSurvey PanelSurvey1;
        
        /// <summary>
        /// PanelContentImageSport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentImageSport PanelContentImageSport1;
        
        /// <summary>
        /// PanelSmallCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox1;
        
        /// <summary>
        /// PanelSmallCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox2;
        
        /// <summary>
        /// PanelSmallCateBox3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox3;
        
        /// <summary>
        /// PanelAdvC4_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC4 PanelAdvC4_1;
        
        /// <summary>
        /// PanelTheodong1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.PanelTheodong PanelTheodong1;
    }
}
