//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Sport {
    
    
    /// <summary>
    /// NewsDetail class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class NewsDetail {
        
        /// <summary>
        /// PanelContentNewsPath1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentNewsPath PanelContentNewsPath1;
        
        /// <summary>
        /// PanelContentNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentNews PanelContentNews1;
        
        /// <summary>
        /// PanelAdvB1_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvB1 PanelAdvB1_1;
        
        /// <summary>
        /// PanelContentListFeedback1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.News.PanelContentListFeedback PanelContentListFeedback1;
        
        /// <summary>
        /// PanelContentListFeedback2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentListFeedback1 PanelContentListFeedback2;
        
        /// <summary>
        /// PanelNewsFeedback1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelNewsFeedback PanelNewsFeedback1;
        
        /// <summary>
        /// PanelHotNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelHotNews PanelHotNews1;
        
        /// <summary>
        /// PanelOtherNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelOtherNews PanelOtherNews1;
        
        /// <summary>
        /// PanelAdvC5_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC5 PanelAdvC5_1;
        
        /// <summary>
        /// PanelGame1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.UserControls.Survey.PaneGame PanelGame1;
        
        /// <summary>
        /// PanelContentImageSport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentImageSport PanelContentImageSport1;
        
        /// <summary>
        /// PanelAdvC6_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC6 PanelAdvC6_1;
        
        /// <summary>
        /// PanelContentSportComment1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentSportComment PanelContentSportComment1;
        
        /// <summary>
        /// PanelAdvC7_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC7 PanelAdvC7_1;
        
        /// <summary>
        /// PanelAdvC4_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC4 PanelAdvC4_1;
        
        /// <summary>
        /// PanelTheodong1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.PanelTheodong PanelTheodong1;
        
        /// <summary>
        /// PanelArticleTracking1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.V1.UserControls.News.PanelArticleTracking PanelArticleTracking1;
    }
}
