//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.Sport {
    
    
    /// <summary>
    /// Search class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Search {
        
        /// <summary>
        /// PanelSearchContent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Search.PanelSearchContent PanelSearchContent1;
        
        /// <summary>
        /// PanelMostRead1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Categories.PanelMostRead PanelMostRead1;
        
        /// <summary>
        /// PanelSurvey1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.UserControls.Survey.PaneSurvey PanelSurvey1;
        
        /// <summary>
        /// PanelContentImageSport2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.News.PanelContentImageSport PanelContentImageSport2;
        
        /// <summary>
        /// PanelAdvC6_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC6 PanelAdvC6_2;
        
        /// <summary>
        /// PanelSmallCateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox1;
        
        /// <summary>
        /// PanelSmallCateBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Homepage.PanelSmallCateBox PanelSmallCateBox2;
        
        /// <summary>
        /// PanelAdvC7_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC7 PanelAdvC7_2;
        
        /// <summary>
        /// PanelAdvC4_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.Advertisements.PanelAdvC4 PanelAdvC4_2;
        
        /// <summary>
        /// PanelTheodong2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.Sport.UserControls.PanelTheodong PanelTheodong2;
    }
}
