<%@ Page MasterPageFile="~/Default.Master" Language="C#" AutoEventWireup="true" Codebehind="Default.aspx.cs"
  Inherits="VietNamNet.Websites.HSBC._Default" %>

<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="cplhContainer">
  <div class="home_right">
    <%--<div class="homepic">
      <img alt="" src="/images/The-le-cuoc-thi.jpg" /></div>--%>
    <div class="home_thele" style="float:none;width:auto;">
      <h2>
        Thể lệ cuộc thi</h2>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><i><span>Với khẩu hiệu “Thế giới sẽ thuộc về những ai biết khám phá tiềm năng”, Ngân hàng TNHH một thành viên HSBC (Việt Nam) (gọi tắt là “HSBC”) lần đầu tiên tổ chức cuộc thi “Khám phá tiềm năng” trên trang web </span></i><span><a href="http://cunghsbckhamphatiemnang.vietnamnet.vn/"><span style="color: #0000ff;">cunghsbckhamphatiemnang.vietnamnet.vn</span></a><a href="http:///"></a>. </span><i>Đây là sân chơi dành cho tất cả những ai yêu thích sự tìm tòi, khám phá và dám đi đến tận cùng những khám phá của mình. Là một Ngân hàng toàn cầu am hiểu địa phương, với kinh nghiệm trên 145 năm, có mặt tại hơn 80 quốc gia và vùng lãnh thổ, HSBC mong muốn tạo ra những chương trình, hoạt động cũng như phương thức hỗ trợ ý nghĩa để giúp ngày càng có nhiều người khám phá được nhiều tiềm năng và trở nên thành công. </i></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><i><span>     Đồng hành cùng cuộc thi, những người đã rất thành công trong việc khám phá những tiềm năng trong công việc và cuộc sống gồm Ông Nguyễn Minh Trí – Doanh nhân Mỹ gốc Châu Á xuất sắc nhất 2010 và Hoa hậu - Ảo thuật gia Ngô Mỹ Uyên sẽ cùng giao lưu trực tuyến với thí sinh dự thi về cách tham gia cuộc thi cũng như chia sẻ tiềm năng, con đường mà họ đã mạnh dạn đã khám phá để biến ước mơ thành hiện thực và trở thành những người thành đạt của ngày hôm nay.</span></i></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>1.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>ĐỐI TƯỢNG THAM GIA: </b>Tất cả công dân Việt Nam từ 18 tuổi trở lên.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>2.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>THỜI GIAN CUỘC THI:</b><span> Từ ngày 24/07/2010 – 15/08/2010. <b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>3.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>CÁCH THỨC THAM GIA CUỘC THI:</b></p>
<img alt=""width="400" style="float: right; margin-left: 12px; margin-right: 12px;" src="/images/demo2.jpg" />
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>a.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">    </span></span></b><b>Cách thức dự thi</b>: </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Người dự thi sẽ viết một bài bằng tiếng Việt (tối đa 500 chữ, có thể kèm hình ảnh minh họa) thể hiện những khám phá, phát hiện của cá nhân về những tiềm năng, cơ hội liên quan đến các lĩnh vực kinh tế, văn hóa nghệ thuật, giáo dục, xã hội… ở Việt Nam hoặc trên thế giới. Tiềm năng đó có thể đã, đang hoặc chưa được khai thác.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><span>Bài dự thi phải đính kèm với bản thông tin cá nhân (Họ tên, Số CMND, năm sinh, nghề nghiệp, địa chỉ, số điện thọai liên lạc) và gửi về địa chỉ email: <a href="mailto:cunghsbckhamphatiemnang@gmail.com"><span style="color: #0000ff;">cunghsbckhamphatiemnang@gmail.com</span></a></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><span>Hàng tuần, những bài dự thi đạt yêu cầu sẽ được chọn đăng tải trên trang web <a href="http://cunghsbckhamphatiemnang.vietnamnet.vn/"><span style="color: #0000ff;">cunghsbckhamphatiemnang.vietnamnet.vn</span></a> </span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><b>Số lượng dự thi</b>: Không hạn chế số lượng bài tham gia dự thi.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"> </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>b.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>Quy định</b><span>:  </span><b></b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Bài dự thi không được có nội dung vi phạm pháp luật hoặc thuần phong mỹ tục Việt Nam cũng như không được đề cập hoặc liên quan đến các vấn đề chính trị, tôn giáo.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Bài dự thi có thể lấy tư liệu hoặc tham khảo từ những bài viết trên các kênh thông tin như sách báo, website, v.v nhưng không được sao chép nguyên văn các tư liệu hay bài viết này dưới bất kỳ hình thức nào. </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Bất kỳ bài dự thi nào đã được sử dụng để tham gia cho bất kỳ cuộc thi nào có nội dung tương tự sẽ không được chấp nhận cho cuộc thi này.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"> </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>4.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>TIÊU CHÍ CHẤM GIẢI:</b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Giá trị của tiềm năng (50%)</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Tính khả thi khai thác tiềm năng (40%)</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Dẫn cứ: nguồn, tài liệu, số liệu, hình ảnh (10%) </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 45pt;"><b></b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>5.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>CƠ CẤU GIẢI THƯỞNG:</b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span><b>1 Giải nhất: </b><span> 1 chuyến du lịch Hồng Kông dành cho 2 người và thẻ thanh toán HSBC với tổng trị giá 38.000.000VNĐ (tương đương 2.000USD)<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span><b>1 Giải nhì: </b><span> 1 chuyến du lịch Singapore dành cho 2 người và thẻ thanh toán HSBC với tổng trị giá 28.500.000VNĐ (tương đương 1.500USD)<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span><b>1 Giải ba: </b><span> 1 chuyến du lịch Sapa Việt Nam dành cho 2 người và thẻ thanh toán HSBC với tổng trị giá 19.000.000VNĐ (tương đương 1.000USD)<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b></b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>6.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>CÁCH THỨC TRAO GIẢI:</b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><span>Ban tổ chức (BTC) sẽ trao cho những người đoạt giải trong buổi tổng kết cuộc thi (thời gian sẽ được thông báo sau).<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><span>Khi đến nhận giải thưởng, người đoạt giải cần cung cấp giấy tờ và các thông tin cần thiết theo yêu cầu của BTC để xác nhận các thông tin như họ tên đầy đủ, Số CMND, Điện thoại, Email mà người đoạt giải đã đăng ký ban đầu.<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><span>Trong trường hợp người đoạt giải không tới nhận giải thưởng trực tiếp mà ủy quyền cho người khác thì người được ủy quyền phải có giấy ủy quyền hợp lệ của người đoạt giải. (Giấy ủy quyền được xem là hợp lệ nếu có đầy đủ thông tin về họ tên, số CMND, địa chỉ liên hệ, điện thoại của người ủy quyền và người được ủy quyền và phải được cơ quan địa phương có thẩm quyền xác nhận).<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span><span>Người đoạt giải chịu mọi chi phí đi lại, ăn ở và các chi phí khác phát sinh liên quan đến việc nhận thưởng.<b></b></span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>7.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>TRÁCH NHIỆM THÔNG BÁO</b> </p>
<p style="text-align: justify; line-height: 140%; margin: 0in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Người đoạt giải trong cuộc thi sẽ do BTC lựa chọn dựa trên tiêu chí chấm giải. </p>
<p style="text-align: justify; line-height: 140%; margin: 0in 0in 0pt 0.25in;"><span><span style="font-family: calibri;">-</span><span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">          </span></span>Người đoạt giải sẽ được thông báo bằng thư bảo đảm, e-mail, điện thoại chậm nhất là sau 07 ngày kể từ ngày kết thúc cuộc thi (đến hết ngày 15 tháng 08 năm 2010).</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>8.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>BAN GIÁM KHẢO CUỘC THI:</b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span>Ông Nguyễn Vũ Phương - Tổng Giám Đốc Gigate Corp - Tập đoàn nhận nhượng quyền thương mại chuỗi nhà hàng lẩu tươi MK tại Việt Nam </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span>Ông Nguyễn Minh Trí – Doanh nhân Mỹ gốc Châu Á xuất sắc nhất 2010</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span>Hoa hậu - Ảo thuật gia Ngô Mỹ Uyên </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>-<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">       </span></span>Ông Thái Đức Huy – Giám đốc Thương hiệu Ngân hàng TNHH một thành viên HSBC (Việt Nam)</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"> </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>9.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">   </span></span></b><b>THÔNG TIN VỀ CUỘC THI:</b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><span>     Mọi thông tin liên quan về cuộc thi có thể truy cập tại trang <a href="http://cunghsbckhamphatiemnang.vietnamnet.vn/"><span style="color: #0000ff;">cunghsbckhamphatiemnang.vietnamnet.vn</span></a> hoặc liên hệ số điện thoại (08) 2.2171172. </span></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b></b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>10.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">        </span></span></b><b><span> CÁC QUY ĐỊNH KHÁC:</span></b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.1.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>Người dự thi cần điền đúng và đầy đủ thông tin bắt buộc (họ tên, CMND, địa chỉ email, địa chỉ liên lạc, số điện thoại). </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.2.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>Các bài dự thi tham gia phải sử dụng hình ảnh, ngôn từ phù hợp với thuần phong mỹ tục của Việt Nam. Người tham gia cuộc thi đồng ý rằng BTC có quyền chỉnh sửa nội dung bài dự thi để đảm bảo sự trong sáng của tiếng Việt khi BTC thấy cần thiết, trước khi đăng tải trên trang web của cuộc thi. </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.3.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>Khi được BTC thông báo đoạt giải, người đoạt thưởng phải xác nhận với BTC những thông tin theo yêu cầu của BTC và xác nhân việc nhận giải. Người tham gia cuộc thi đồng ý rằng BCT có thể sử dụng thông tin, hình ảnh và bài dự thi của người tham gia cuộc thi trong các chiến dịch quảng bá về chương trình.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.4.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>Nếu người đoạt giải không liên lạc được với BTC trong thời hạn 30 ngày sau khi BTC gửi thông báo kết quả giải thưởng, hoặc người đoạt giải không xác nhận hợp lệ các thông tin cá nhân theo yêu cầu của BTC, hoặc không hoàn tất việc thông báo và xác nhận trúng thưởng theo yêu cầu của BTC, giải thưởng có thể bị thu hồi và BTC được phép chọn người thắng cuộc mới dựa trên quyết định mới của BGK. Nếu BTC không thể liên lạc được với người trúng thưởng, BTC cũng sẽ lựa chọn một người thắng cuộc mới dựa trên kết quả mới của BGK.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.5.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>HSBC không chịu trách nhiệm về: (i) các đăng ký dự thi không thành công xảy ra do lỗi trang web, đường truyền Internet bị gián doạn hoặc quá tải, virus máy tính, tin tặc xâm nhập hủy dữ liệu, dữ liệu bị hư hỏng, hư hại phần cứng, phần mềm và các lý do khác khiến việc đăng ký không thành công; (ii) tư cách người dự thi hoặc e-mail không hợp lệ; (iii) bất kỳ sự kiện tạo ra bởi chương trình vượt tầm quản lý của BTC có thể làm cuộc thi bị ngắt quãng và hủy bỏ; (iv) những quà tặng đã trao bị thất lạc, hư hại hoặc đánh mất () bất kỳ lỗi chữ trong tất cả các dữ liệu của cuộc thi.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.6.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>HSBC sẽ không chịu trách nhiệm về bất kỳ tổn thất nào do lỗi từ người tham dự và những thất thoát, chi phí phát sinh liên quan đến việc nhận giải thưởng.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.7.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>Khách hàng trúng giải phải tự chịu trách nhiệm về khoản thuế thu nhập cá nhân (TNCN) theo quy định của pháp luật Việt Nam hiện hành. Ban Tổ Chức sẽ khấu trừ khoản thuế TNCN này từ người trúng thưởng trước khi trao giải. BTC sẽ thông tin về số tiền thuế TNCN mà người trúng giải phải nộp khi thông báo trúng giải.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.8.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>BTC có thẩm quyền quyết định hoãn lại hay hủy bỏ cuộc thi ở bất kể thời điểm nào do xảy ra trường hợp bất khả kháng (bao gồm nhưng không giới hạn như máy tính bị nhiễm virus, bị lỗi hay các vấn đề kỹ thuật khác làm gián đoạn sự quản lý, bảo mật). BTC cũng có quyền thay đổi nội dung cuộc thi, hay điều chỉnh thể lệ vào bất kì thời điểm nào trước khi kết thúc cuộc thi và sẽ đăng tải thể lệ đã chỉnh sửa trên website (nếu có). </p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.9.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">     </span></span>Quyết định của BTC là quyết định cuối cùng.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.10.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">  </span></span>Giải thưởng không được chuyển nhượng cho người khác và không được quy đổi thành tiền mặt. BTC có quyền thay thế bất cứ quà tặng nào có giá trị tương đương.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.11.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">  </span></span>Các cán bộ, nhân viên của HSBC, các công ty liên kết, chi nhánh của HSBC; các đối tác thực hiện chiến dịch truyền thông, quảng cáo, xúc tiến chương trình và thân nhân của những thành viên nêu trên không được tham gia cuộc thi.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.12.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">  </span></span>Trong trường hợp xảy ra tranh chấp liên quan đến chương trình khuyến mại này, Ban Tổ Chức có trách nhiệm trực tiếp giải quyết, nếu không thỏa thuận được tranh chấp sẽ được xử lý theo quy định của pháp luật Việt Nam hiện hành.</p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 58.5pt;"><span>10.13.<span style="line-height: normal; font-variant: normal; font-style: normal; font-size: 7pt; font-weight: normal;">  </span></span>Đối với những giải thưởng không có người trúng thưởng, BTC sẽ trích nộp 50% (năm mươi phần trăm) giá trị đã công bố của giải thưởng đó vào ngân sách nhà nước theo quy định tại khoản 4 Điều 96 Luật Thương mại.</p>
<p style="text-align: right; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"><b><span>BAN TỔ CHỨC</span></b></p>
<p style="text-align: justify; line-height: 140%; margin: 0.2in 0in 0pt 0.25in;"> </p>
<p style="margin: 0in 0in 10pt;"><span style="font-family: calibri;"> </span></p>
<p style="margin: 0in 0in 10pt;"><span style="font-family: calibri;"> </span></p>
      <div class="downloadthele">
        <a href="/Lib/TheLeCuocThi.doc">
          <img alt="" src="/images/download_thele.gif" /></a></div>
    </div>
    <div class="clearall">
    </div>
  </div>
</asp:Content>
