//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamNet.Websites.English.UserControls.News {
    
    
    /// <summary>
    /// PanelContentNews class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class PanelContentNews {
        
        /// <summary>
        /// rptContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptContent;
        
        /// <summary>
        /// PanelContentPhoto1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentPhoto PanelContentPhoto1;
        
        /// <summary>
        /// PanelContentVideo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VietNamNet.Websites.English.UserControls.News.PanelContentVideo PanelContentVideo1;
    }
}
